version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      target-branch: 'beta'
      ignore:
          - dependency-name: 'node-fetch'
            versions: ['3.x']
